### PR TITLE
created a preliminary BOM spreadsheet (LibreOffice)

### PR DESCRIPTION
**Pull request by smarkoco**
The spreadsheet has my best attempt at including all parts from your amazing cadlab.io project (except connectors and some other less essential components). I also made an attempt to fill in most of the gaps. Please feel free to make suggestions about anything if I'm wrong somewhere. I've also added several lines which have "??????" listed for the part number, which are parts that I couldn't figure out, such as the connector to the battery and the connector from the PWM pins and to the motors ... is there a Electronic Speed Controller? Thanks!!

image

### CODE REVIEW

**Comment by smarkoco** [comment]
just realized, I probably shoud've either put this in `./electronics` or `./misc` folders-- feel free to let me know and I can move it

**Comment by dridri** [comment]
Hello, sorry for seeing your PR a bit late (I found a new job, and first weeks are always a little intense).
Well done ! That must have been tough for certain parts.
I actually don't have a BOM anywhere and did just buy on Mouser by searching by package / voltage / etc, but I could probably help you by taking a look at my orders history :

Camera connectors : https://www.mouser.fr/ProductDetail/798-FH12A-22S0.5SH55
J9 (battery) : https://www.mouser.fr/ProductDetail/Amphenol-FCI/54102-T05-00?qs=DhjuHb%2FCp76wM1OXM2Bzdw%3D%3D
PWM0-3 : https://www.mouser.fr/ProductDetail/Samtec/TSW-104-22-T-T-RA?qs=rU5fayqh%252BE0ybDtoC9UCtQ%3D%3D
PWM4-7 : solder pads

C9 : I actually never installed a magnetometer so I don't know, but any 4.7uF @6.3V will do

R8, R9 : https://www.mouser.fr/ProductDetail/71-CRCW0603330RJNEAC
D3, D4 : Can't find them in my orders, but since the resistors are 330ohm any 0805 @20mA should be ok
AE1, AE2 : U.FL antenna connector : https://www.mouser.fr/ProductDetail/Hirose-Connector/U.FL-R-SMT10?qs=Ux3WWAnHpjBT1CWD8UMEMQ%3D%3D

SD1 : https://www.mouser.fr/ProductDetail/798-DM3AT-SF-PEJM5
C1 : can't find, bu just a decoupling capacitor, any 0603 10µF @6.3V is ok

SBUS1 : solder pads

**Comment by smarkoco** [comment]
Cool, thanks! I just updated all those, so everything should now be accurate

**Comment by smarkoco** [comment]
By the way, congrats on the new job!! Yeah totally understand the hectic phase of getting up to speed on new projects/enviroment, hope it's going well

**Comment by dridri** [comment]
Ready to merge the PR ?

**Pull request merged**
